### ISSUE TITLE
Naive traceback

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-softimage#1]
Simply running QML from Softimage as-is produces the following exception.

```
# Traceback (most recent call last):
#   File "c:\pythonpath\pyblish_rpc\service.py", line 117, in _dispatch
#     return func(*params)
#   File "c:\pythonpath\pyblish_rpc\service.py", line 76, in discover
#     return formatting.format_plugins(self._plugins)
#   File "c:\pythonpath\pyblish_rpc\formatting.py", line 211, in format_plugins
#     formatted_plugin = format_plugin(plugin_)
#   File "c:\pythonpath\pyblish_rpc\formatting.py", line 254, in format_plugin
#     module = sys.modules[plugin.__module__]
# KeyError: '__ax_main__'
```

**Comment by mottosso** [comment]
This had to do with the fact that plug-ins created in the Softimage terminal wasn't given the standard `__main__` module name. Fixed by making Pyblish RPC more permissive.
